services:
  - type: web
    name: motorsports-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 backend/app.py"
    autoDeploy: true
    branch: main
    region: oregon
    rootDir: .