services:
  - type: web
    name: motorsports-api
    env: python
    plan: free
    buildCommand: |
      python3 -m venv venv && \
      . venv/bin/activate && \
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate && \
      python3 backend/app.py
    autoDeploy: true
    branch: main
    region: Virginia (US East)
    rootDir: .
