services:
  - type: web
    name: motorsports-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/app.py"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
    branch: main
    region: oregon
    rootDir: .